# fly.toml app configuration file generated for mcp-return-reminder-tailscale on 2025-08-11T12:29:21-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mcp-return-reminder-tailscale'
primary_region = 'sjc'

[build]
  dockerfile = './Dockerfile'

[env]
  NODE_ENV = 'production'
  PORT = '3000'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
