# Deploy to Dokku on Google Compute Engine
name: Deploy to GCE Dokku

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy to Dokku
    runs-on: ubuntu-latest
    concurrency: deploy-group-gce

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy to Dokku on GCE
        uses: dokku/github-action@master
        with:
          git_remote_url: ${{ secrets.GCE_GIT_REMOTE_URL }}
          ssh_host_key: ${{ secrets.GCE_SSH_HOST_KEY }}
          ssh_private_key: ${{ secrets.GCE_SSH_PRIVATE_KEY }}
          deploy: main
          git_push_flags: --force
